package co.edu.uniminuto.arqSw.proyectoEstampas.Hibernate;
// Generated 22/03/2018 11:33:32 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Camisetas generated by hbm2java
 */
public class Camisetas  implements java.io.Serializable {


     private int idCamisetas;
     private String talla;
     private String color;
     private String estilo;
     private Set<FacturaVenta> facturaVentas = new HashSet<FacturaVenta>(0);

    public Camisetas() {
    }

	
    public Camisetas(int idCamisetas, String talla, String color, String estilo) {
        this.idCamisetas = idCamisetas;
        this.talla = talla;
        this.color = color;
        this.estilo = estilo;
    }
    public Camisetas(int idCamisetas, String talla, String color, String estilo, Set<FacturaVenta> facturaVentas) {
       this.idCamisetas = idCamisetas;
       this.talla = talla;
       this.color = color;
       this.estilo = estilo;
       this.facturaVentas = facturaVentas;
    }
   
    public int getIdCamisetas() {
        return this.idCamisetas;
    }
    
    public void setIdCamisetas(int idCamisetas) {
        this.idCamisetas = idCamisetas;
    }
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getEstilo() {
        return this.estilo;
    }
    
    public void setEstilo(String estilo) {
        this.estilo = estilo;
    }
    public Set<FacturaVenta> getFacturaVentas() {
        return this.facturaVentas;
    }
    
    public void setFacturaVentas(Set<FacturaVenta> facturaVentas) {
        this.facturaVentas = facturaVentas;
    }




}


