package co.edu.uniminuto.arqSw.proyectoEstampas.Hibernate;
// Generated 22/03/2018 11:33:32 PM by Hibernate Tools 3.6.0



/**
 * FacturaVentaId generated by hbm2java
 */
public class FacturaVentaId  implements java.io.Serializable {


     private int idFacturaVenta;
     private int usuarioIdUsuario;
     private int camisetasIdCamisetas;
     private int estampasIdEstampas;

    public FacturaVentaId() {
    }

    public FacturaVentaId(int idFacturaVenta, int usuarioIdUsuario, int camisetasIdCamisetas, int estampasIdEstampas) {
       this.idFacturaVenta = idFacturaVenta;
       this.usuarioIdUsuario = usuarioIdUsuario;
       this.camisetasIdCamisetas = camisetasIdCamisetas;
       this.estampasIdEstampas = estampasIdEstampas;
    }
   
    public int getIdFacturaVenta() {
        return this.idFacturaVenta;
    }
    
    public void setIdFacturaVenta(int idFacturaVenta) {
        this.idFacturaVenta = idFacturaVenta;
    }
    public int getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(int usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }
    public int getCamisetasIdCamisetas() {
        return this.camisetasIdCamisetas;
    }
    
    public void setCamisetasIdCamisetas(int camisetasIdCamisetas) {
        this.camisetasIdCamisetas = camisetasIdCamisetas;
    }
    public int getEstampasIdEstampas() {
        return this.estampasIdEstampas;
    }
    
    public void setEstampasIdEstampas(int estampasIdEstampas) {
        this.estampasIdEstampas = estampasIdEstampas;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaVentaId) ) return false;
		 FacturaVentaId castOther = ( FacturaVentaId ) other; 
         
		 return (this.getIdFacturaVenta()==castOther.getIdFacturaVenta())
 && (this.getUsuarioIdUsuario()==castOther.getUsuarioIdUsuario())
 && (this.getCamisetasIdCamisetas()==castOther.getCamisetasIdCamisetas())
 && (this.getEstampasIdEstampas()==castOther.getEstampasIdEstampas());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFacturaVenta();
         result = 37 * result + this.getUsuarioIdUsuario();
         result = 37 * result + this.getCamisetasIdCamisetas();
         result = 37 * result + this.getEstampasIdEstampas();
         return result;
   }   


}


