package co.edu.uniminuto.arqSw.proyectoEstampas.Hibernate;
// Generated 22/03/2018 11:33:32 PM by Hibernate Tools 3.6.0



/**
 * FacturaVenta generated by hbm2java
 */
public class FacturaVenta  implements java.io.Serializable {


     private FacturaVentaId id;
     private Usuario usuario;
     private Camisetas camisetas;
     private Estampas estampas;
     private String fecha;
     private String direccion;
     private Integer cantidad;
     private String formaPago;
     private Integer valorArtista;
     private Integer valorEmpresa;
     private Integer valorAdicionalTexto;
     private Integer valorNeto;
     private Integer valorTotal;

    public FacturaVenta() {
    }

	
    public FacturaVenta(FacturaVentaId id, Usuario usuario, Camisetas camisetas, Estampas estampas) {
        this.id = id;
        this.usuario = usuario;
        this.camisetas = camisetas;
        this.estampas = estampas;
    }
    public FacturaVenta(FacturaVentaId id, Usuario usuario, Camisetas camisetas, Estampas estampas, String fecha, String direccion, Integer cantidad, String formaPago, Integer valorArtista, Integer valorEmpresa, Integer valorAdicionalTexto, Integer valorNeto, Integer valorTotal) {
       this.id = id;
       this.usuario = usuario;
       this.camisetas = camisetas;
       this.estampas = estampas;
       this.fecha = fecha;
       this.direccion = direccion;
       this.cantidad = cantidad;
       this.formaPago = formaPago;
       this.valorArtista = valorArtista;
       this.valorEmpresa = valorEmpresa;
       this.valorAdicionalTexto = valorAdicionalTexto;
       this.valorNeto = valorNeto;
       this.valorTotal = valorTotal;
    }
   
    public FacturaVentaId getId() {
        return this.id;
    }
    
    public void setId(FacturaVentaId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Camisetas getCamisetas() {
        return this.camisetas;
    }
    
    public void setCamisetas(Camisetas camisetas) {
        this.camisetas = camisetas;
    }
    public Estampas getEstampas() {
        return this.estampas;
    }
    
    public void setEstampas(Estampas estampas) {
        this.estampas = estampas;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public Integer getValorArtista() {
        return this.valorArtista;
    }
    
    public void setValorArtista(Integer valorArtista) {
        this.valorArtista = valorArtista;
    }
    public Integer getValorEmpresa() {
        return this.valorEmpresa;
    }
    
    public void setValorEmpresa(Integer valorEmpresa) {
        this.valorEmpresa = valorEmpresa;
    }
    public Integer getValorAdicionalTexto() {
        return this.valorAdicionalTexto;
    }
    
    public void setValorAdicionalTexto(Integer valorAdicionalTexto) {
        this.valorAdicionalTexto = valorAdicionalTexto;
    }
    public Integer getValorNeto() {
        return this.valorNeto;
    }
    
    public void setValorNeto(Integer valorNeto) {
        this.valorNeto = valorNeto;
    }
    public Integer getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(Integer valorTotal) {
        this.valorTotal = valorTotal;
    }




}


