package co.edu.uniminuto.arqSw.proyectoEstampas.Hibernate;
// Generated 22/03/2018 11:33:32 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombre;
     private String correo;
     private String password;
     private String tipoUsuario;
     private String telefono;
     private String direccion;
     private Set<FacturaVenta> facturaVentas = new HashSet<FacturaVenta>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(int idUsuario, String nombre, String correo, String password, String tipoUsuario, String telefono, String direccion, Set<FacturaVenta> facturaVentas) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.correo = correo;
       this.password = password;
       this.tipoUsuario = tipoUsuario;
       this.telefono = telefono;
       this.direccion = direccion;
       this.facturaVentas = facturaVentas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<FacturaVenta> getFacturaVentas() {
        return this.facturaVentas;
    }
    
    public void setFacturaVentas(Set<FacturaVenta> facturaVentas) {
        this.facturaVentas = facturaVentas;
    }




}


